/* PROCEDURE PARA FOLHA DE PAGAMENTO */
USE tsql_erpProject
GO

CREATE PROCEDURE PROC_FOLHA
	(@COD_EMPRESA INT,
	@MES_REF INT,
	@ANO_REF INT,
	@DATA_PAGTO DATE)
AS
BEGIN

	DECLARE @MATRICULA INT,
		@SALARIO_BRUTO DECIMAL(10,2),
		@SALARIO_LIQ DECIMAL(10,2),
		@PCT_INSS DECIMAL(10,2),
		@VAL_INSS DECIMAL(10,2),
		@PCT_IRPF DECIMAL(10,2),
		@VAL_IRPF DECIMAL(10,2),
		@VAL_ISENT_IRPF DECIMAL(10,2)

	BEGIN TRANSACTION
	BEGIN TRY 

-- Apaga registros para recalcular
SELECT 'Apagando registros para recalcular.'
DELETE FROM FOLHA_PAGTO WHERE COD_EMPRESA = @COD_EMPRESA AND MES_REF = @MES_REF AND ANO_REF = @ANO_REF

-- Declaração de cursor para ler o salário do funcionário
DECLARE SAL_BRUTO CURSOR FOR
-- Seleciona valores
	SELECT A.MATRICULA MATRICULA, A.SALARIO SAL_BRUTO
	FROM SALARIO A
		INNER JOIN FUNCIONARIO B
		ON A.COD_EMPRESA = B.COD_EMPRESA
			AND A.MATRICULA = B.MATRICULA
	WHERE A.COD_EMPRESA = @COD_EMPRESA
		AND B.DATE_DEMISS='1900-01-01' -- Equivalente à data nula
		AND MONTH(B.DATA_ADMISS) <= @MES_REF
		AND YEAR (B.DATA_ADMISS) <= @ANO_REF

-- Abre o cursor
  OPEN SAL_BRUTO

  FETCH NEXT FROM SAL_BRUTO
-- Insere valores em variáveis 
  INTO @MATRICULA,@SALARIO_BRUTO 
	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- Projeta registros
		SELECT @MATRICULA MATRICULA, @SALARIO_BRUTO SALARIO_BRUTO
		-- Insere o salário bruto na FOLHA_PAGTO
		INSERT INTO FOLHA_PAGTO
		VALUES
			(@COD_EMPRESA, @MATRICULA, 'F', 'P', 'SAL BRUTO', @MES_REF, @ANO_REF, @DATA_PAGTO, @SALARIO_BRUTO);

		-- Declaração de cursor para cálculo de INSS
		DECLARE  CALC_INSS CURSOR FOR

    --SELECT * FROM PARAM_INSS
    SELECT A.PCT
		FROM PARAM_INSS A
		WHERE @SALARIO_BRUTO BETWEEN A.VALOR_DE AND A.VALOR_ATE
			AND @MES_REF BETWEEN MONTH(A.VIGENCIA_INI) AND MONTH(A.VIGENCIA_FIM)
			AND @ANO_REF BETWEEN YEAR(A.VIGENCIA_INI) AND YEAR(A.VIGENCIA_FIM)

		-- Abertura de cursor 
		OPEN CALC_INSS

		FETCH NEXT FROM CALC_INSS
-- Insere valor em variável 
  INTO @PCT_INSS
		WHILE @@FETCH_STATUS = 0
    
	BEGIN
			-- Regra de teto, qunado valor for maior que 5531.31

			IF @SALARIO_BRUTO > 5531.31
		BEGIN
				SET @VAL_INSS = 608.44
				SET @PCT_INSS = 0
			END 
		 ELSE
		  BEGIN
				SET @VAL_INSS = @SALARIO_BRUTO/100 * @PCT_INSS
			END

			-- Projeta valores
			SELECT 'CALC INSS', @PCT_INSS PCT_INSS, @VAL_INSS VAL_INSS

			-- Insere registros na FOLHA_PAGTO
			INSERT INTO FOLHA_PAGTO
			VALUES
				(@COD_EMPRESA, @MATRICULA, 'F', 'D', 'INSS', @MES_REF, @ANO_REF, @DATA_PAGTO, @VAL_INSS);

			-- Declaração de cursor para cálculo de IRRF 	
			DECLARE CALC_IRRF CURSOR FOR

		SELECT A.PCT, A.VAL_ISENT
			FROM PARAM_IRRF A
			WHERE @SALARIO_BRUTO BETWEEN A.VALOR_DE AND A.VALOR_ATE
				AND @MES_REF BETWEEN MONTH(A.VIGENCIA_INI) AND MONTH(A.VIGENCIA_FIM)
				AND @ANO_REF BETWEEN YEAR(A.VIGENCIA_INI) AND YEAR(A.VIGENCIA_FIM)

			-- Abre o cursor	
			OPEN CALC_IRRF

			FETCH NEXT FROM CALC_IRRF
		INTO @PCT_IRPF,@VAL_ISENT_IRPF

			WHILE @@FETCH_STATUS = 0
		  BEGIN
				-- Calcula IR
				SET @VAL_IRPF=((@SALARIO_BRUTO - @VAL_INSS)/100) * @PCT_IRPF - @VAL_ISENT_IRPF
				-- Projeta valor
				SELECT 'CALC IRRF', @PCT_IRPF AS PCT_IRPF, @VAL_IRPF AS VAL_IRPF
				-- Insere valor de IR na FOLHA_PAGTO
				INSERT INTO FOLHA_PAGTO
				VALUES
					(@COD_EMPRESA, @MATRICULA, 'F', 'D', 'IRRF', @MES_REF, @ANO_REF, @DATA_PAGTO, @VAL_IRPF);


				FETCH NEXT FROM CALC_IRRF
			INTO @PCT_IRPF, @VAL_ISENT_IRPF
			END
			-- Fecha e desaloca cursor de IRRF
			CLOSE CALC_IRRF
			DEALLOCATE CALC_IRRF

			-- Próxima linha do cursor CALC_INSS
			FETCH NEXT FROM CALC_INSS
  INTO @PCT_INSS
		END
		-- Fecha e desaloca cursor de CALC_INSS
		CLOSE CALC_INSS
		DEALLOCATE CALC_INSS

		-- Apresenta valores
		SELECT 'TOTAL DESCONTO', @VAL_INSS + @VAL_IRPF
		SET @SALARIO_LIQ = @SALARIO_BRUTO - (@VAL_INSS+@VAL_IRPF)
		SELECT 'SALARIO LIQUIDO', @SALARIO_LIQ AS VAL_LIQ
		INSERT INTO FOLHA_PAGTO
		VALUES
			(@COD_EMPRESA, @MATRICULA, 'F', 'P', 'SALARIO LIQUIDO', @MES_REF, @ANO_REF, @DATA_PAGTO, @SALARIO_LIQ);
		FETCH NEXT FROM SAL_BRUTO
 INTO @MATRICULA,@SALARIO_BRUTO
	END 

 -- Fecha e desaloca cursor SAL_BRUTO
 CLOSE SAL_BRUTO
 DEALLOCATE SAL_BRUTO

 IF @@ERROR <>0
	 BEGIN
		ROLLBACK
		PRINT 'Operação cancelada.'
	END
	 ELSE
		BEGIN
		PRINT 'Operação finalizada com sucesso.'
		COMMIT
	END

	END TRY
	BEGIN CATCH
		
        print ''
        print 'Ocorreu um erro.'
        print 'Mensagem: ' + ERROR_MESSAGE()
        print 'Procedure: ' + ERROR_PROCEDURE()

		IF (SELECT CURSOR_STATUS('global', 'SAL_BRUTO')) = 1 
		BEGIN
		CLOSE SAL_BRUTO
		DEALLOCATE SAL_BRUTO
	END
		IF (SELECT CURSOR_STATUS('global', 'CALC_INSS')) = 1 
		BEGIN
		CLOSE CALC_INSS
		DEALLOCATE CALC_INSS
	END
		IF (SELECT CURSOR_STATUS('global', 'CALC_IRRF')) = 1 
		BEGIN
		CLOSE CALC_IRRF
		DEALLOCATE CALC_IRRF
	END	
		
		SET XACT_ABORT ON;
		IF @@TRANCOUNT > 0  
        ROLLBACK TRANSACTION; 
	END CATCH

END

-- Teste da procedure
-- Parâmetros -> @COD_EMPRESA,@MES_REF,@ANO_REF,@DATA_PAGTO
EXEC PROC_FOLHA 1,1,2018,'05-02-2018'
EXEC PROC_FOLHA 2,2,2018,'05-02-2018'

SELECT *
FROM FOLHA_PAGTO