/* VIEW FATURAMENTO */

USE tsql_erpProject
GO

CREATE VIEW V_FATURAMENTO
AS
	SELECT A.COD_EMPRESA,
		A.NUM_NF,
		A.ID_CLIFOR,
		CAST(A.DATA_EMISSAO AS DATE) AS DATA_EMISSAO,
		B.COD_MAT,
		C.DESCRICAO,
		D.RAZAO_CLIENTE,
		E.NOME_MUN,
		B.QTD,
		B.VAL_UNIT,
		B.QTD * B.VAL_UNIT AS TOTAL
	FROM NOTA_FISCAL A
		INNER JOIN NOTA_FISCAL_ITENS B ON A.COD_EMPRESA = B.COD_EMPRESA
			AND A.NUM_NF = B.NUM_NF
		INNER JOIN MATERIAL C ON A.COD_EMPRESA = C.COD_EMPRESA
			AND B.COD_MAT = C.COD_MAT
		INNER JOIN CLIENTES D ON A.COD_EMPRESA = D.COD_EMPRESA
			AND A.ID_CLIFOR = D.ID_CLIENTE
		INNER JOIN CIDADES E ON D.COD_CIDADE = E.COD_CIDADE
	WHERE A.TIP_NF = 'S'

-- Teste view
SELECT *
FROM V_FATURAMENTO