/* VIEWS FUNCIONÁRIOS */

USE tsql_erpProject
GO

CREATE VIEW V_FUNCIONARIO
AS
	SELECT A.COD_EMPRESA,
		A.MATRICULA,
		A.COD_CC,
		C.NAME_CC,
		A.NOME,
		A.COD_CARGO,
		B.NOME_CARGO,
		A.DATA_ADMISS,
		A.DATE_DEMISS,
		CASE 
		WHEN A.DATE_DEMISS = '1900-01-01' THEN 'ATIVO'
		ELSE 'DESLIGADO' 
	END AS SITUACAO
	FROM FUNCIONARIO A
		INNER JOIN CARGOS B ON A.COD_EMPRESA = B.COD_EMPRESA
			AND A.COD_CARGO = B.COD_CARGO
		INNER JOIN CENTRO_CUSTO C ON A.COD_CC = C.COD_CC
			AND A.COD_EMPRESA = C.COD_EMPRESA

-- Teste view
SELECT *
FROM V_FUNCIONARIO