/* VIEW NECESSIDADES */

USE tsql_erpProject
GO

CREATE VIEW V_NECESSIDADES
AS
	SELECT A.COD_EMPRESA,
		A.ID_ORDEM,
		A.COD_MAT_PROD,
		A.QTD_PLAN, A.QTD_PROD,
		A.QTD_PLAN-A.QTD_PROD SALDO,
		B.COD_MAT_NECES,
		D.DESCRICAO,
		B.QTD_NECES,
		(A.QTD_PLAN - A.QTD_PROD) * B.QTD_NECES AS QTD_REAL_NEC,
		C.QTD_SALDO,
		CASE 
				WHEN  (A.QTD_PLAN - A.QTD_PROD) * B.QTD_NECES > C.QTD_SALDO
				THEN 'FALTA ESTOQUE' 
				ELSE 'OK' 
			END MSG
	FROM ORDEM_PROD A
		INNER JOIN FICHA_TECNICA B ON A.COD_EMPRESA=B.COD_EMPRESA
			AND A.COD_MAT_PROD=B.COD_MAT_PROD
		INNER JOIN ESTOQUE C ON A.COD_EMPRESA=C.COD_EMPRESA
			AND B.COD_MAT_NECES=C.COD_MAT
		INNER JOIN MATERIAL D ON A.COD_EMPRESA=D.COD_EMPRESA
			AND B.COD_MAT_NECES = D.COD_MAT
	WHERE (A.QTD_PLAN - A.QTD_PROD) != 0

-- Teste view
SELECT *
FROM V_NECESSIDADES
WHERE COD_EMPRESA = '1'
	AND ID_ORDEM = 2