/* VIEW CONTAS A PAGAR */

USE tsql_erpProject
GO

CREATE VIEW V_CONTAS_PAGAR
AS
	SELECT A.COD_EMPRESA,
		A.ID_DOC,
		A.ID_FOR,
		B.RAZAO_FORNEC,
		A.PARC,
		A.DATA_VENC,
		A.DATA_PAGTO,
		A.VALOR,
		CASE 
			WHEN A.DATA_PAGTO IS NULL 
			THEN 'ABERTO' 
			ELSE 'PAGO' 
	   END AS SITUACAO,
		CASE
			WHEN A.DATA_VENC > GETDATE() THEN 'NORMAL' 
			WHEN A.DATA_PAGTO > A.DATA_VENC   THEN 'PAGTO EF COM ATRASO'
	    ELSE 'VENCIDO' END MSG
	FROM CONTAS_PAGAR A
		INNER JOIN FORNECEDORES B
		ON A.COD_EMPRESA=B.COD_EMPRESA
			AND A.ID_FOR=B.ID_FOR

-- Teste view
SELECT *
FROM V_CONTAS_PAGAR