/* VIEW CUSTO PRODUTO */

USE tsql_erpProject
GO

CREATE VIEW V_CUSTO_PRODUTO_DET
AS
	SELECT A.COD_EMPRESA,
		A.COD_MAT,
		A.DESCRICAO,
		B.COD_MAT_NECES,
		C.DESCRICAO DESCRICAO_MAT_N,
		B.QTD_NECES,
		C.PRECO_UNIT,
		B.QTD_NECES*C.PRECO_UNIT CUSTO_NEC
	FROM MATERIAL A
		INNER JOIN FICHA_TECNICA B ON A.COD_EMPRESA=B.COD_EMPRESA
			AND A.COD_MAT=B.COD_MAT_PROD
		INNER JOIN MATERIAL C ON A.COD_EMPRESA=C.COD_EMPRESA
			AND B.COD_MAT_NECES = C.COD_MAT
	WHERE A.COD_TIP_MAT = '2'

-- Teste view
SELECT *
FROM V_CUSTO_PRODUTO_DET