/* VIEW DE RESUMO DE CUSTO */

USE tsql_erpProject
GO

CREATE VIEW V_CUSTO_PRODUTO_RESUMO
AS
	SELECT A.COD_EMPRESA,
		A.COD_MAT,
		A.DESCRICAO,
		A.PRECO_UNIT AS PRECO_VENDA,
		SUM(B.QTD_NECES * C.PRECO_UNIT) AS CUSTO,
		A.PRECO_UNIT-SUM(B.QTD_NECES*C.PRECO_UNIT) AS MARGEM
	FROM MATERIAL A
		INNER JOIN FICHA_TECNICA B ON A.COD_EMPRESA=B.COD_EMPRESA
			AND A.COD_MAT=B.COD_MAT_PROD
		INNER JOIN MATERIAL C ON A.COD_EMPRESA=C.COD_EMPRESA
			AND B.COD_MAT_NECES=C.COD_MAT
	WHERE A.COD_TIP_MAT='2'
	GROUP BY A.COD_EMPRESA,A.COD_MAT,A.DESCRICAO,A.PRECO_UNIT

-- Teste view
SELECT *
FROM V_CUSTO_PRODUTO_RESUMO