/* VIEW CANAL DE VENDAS */

USE tsql_erpProject
GO

CREATE VIEW V_CANAL_VENDAS
AS
	SELECT A.COD_EMPRESA,
		A.ID_CLIENTE,
		A.RAZAO_CLIENTE,
		ISNULL(B.MATRICULA_VEND,0)ID_VEND,
		ISNULL(D.NOME,'SEM CANAL')NOME_VEND,
		ISNULL(E.MATRICULA_GER,0) ID_GER,
		ISNULL(G.NOME,'SEM CANAL') NOME_GER
	FROM CLIENTES A
		LEFT JOIN CANAL_VENDAS_V_C B
		ON A.COD_EMPRESA=B.COD_EMPRESA
			AND A.ID_CLIENTE=B.ID_CLIENTE

		LEFT JOIN VENDEDORES C
		ON A.COD_EMPRESA=C.COD_EMPRESA
			AND B.MATRICULA_VEND = C.MATRICULA

		LEFT JOIN FUNCIONARIO D
		ON A.COD_EMPRESA = D.COD_EMPRESA
			AND C.MATRICULA = D.MATRICULA

		LEFT JOIN CANAL_VENDAS_G_V E
		ON A.COD_EMPRESA=E.COD_EMPRESA
			AND B.MATRICULA_VEND=E.MATRICULA_VEND

		LEFT JOIN GERENTES F
		ON A.COD_EMPRESA=F.COD_EMPRESA
			AND E.MATRICULA_GER=F.MATRICULA

		LEFT JOIN FUNCIONARIO G
		ON A.COD_EMPRESA=G.COD_EMPRESA
			AND F.MATRICULA = G.MATRICULA

--TESTANDO VIEW V_CANAL_VENDAS
SELECT *
FROM V_CANAL_VENDAS