USE TSQL_ERPPROJECT
GO

-- ADD CAMPO LOGIN TABELA NA TABELA APONTAMENTOS 
ALTER TABLE APONTAMENTOS ADD LOGIN VARCHAR(30)NOT NULL;

-- ADD CAMPO LOTE NA TABELA APONTAMENTOS
ALTER TABLE APONTAMENTOS ADD LOTE VARCHAR(20) NOT NULL;

--ADD CAMPO LOGIN NA TABELA ESTOQUE_MOV
ALTER TABLE ESTOQUE_MOV ADD LOGIN VARCHAR(30)NOT NULL;

/* EXAMPLES ONLY FOR STUDY */

-- ADD FOREIGN KEY
ALTER TABLE APONTAMENTOS ADD CONSTRAINT FK_APONT3
  FOREIGN KEY (LOGIN) REFERENCES USUARIOS(LOGIN);

ALTER TABLE ESTOQUE_MOV ADD CONSTRAINT FK_ESTM2
  FOREIGN KEY (LOGIN) REFERENCES USUARIOS(LOGIN);
-- REMOÇÃO DE CONSTRAINT 
ALTER TABLE CONSUMO DROP CONSTRAINT  FK_CONS2
ALTER TABLE APONTAMENTOS DROP CONSTRAINT  FK_APONT3

-- ADD COD_PAGTO DA PED_COMPRAS COMO FOREIGN KEY 
ALTER TABLE PED_COMPRAS ADD 
  FOREIGN KEY (COD_PAGTO) REFERENCES COND_PAGTO(COD_PAGTO);